### ISSUE TITLE
Segmentation fault in a lot of addon.

### ISSUE THREAD

**Issue by darkt1981** [blaxxun-boop/ItemManager#5]
Hi i contacted Wacky about a issue i had with his addon but he asked me to send you this, it seems that your itemmanager update break a lot of addons for other mods. Hope you can use this.

[message.txt](https://github.com/blaxxun-boop/ItemManager/files/11806156/message.txt)

**Comment by blaxxun-boop** [comment]
Nope, no idea why funlockfile crashes on your system.

I can find this: https://steamcommunity.com/sharedfiles/filedetails/?id=2513264126
And this: https://stackoverflow.com/questions/71469169/unity-crashes-on-startup-on-my-linux-machine/72235766#72235766

Not sure if one of these solutions will fix your issue.
