### ISSUE TITLE
error

### ISSUE THREAD

**Issue by darkt1981** [blaxxun-boop/ItemManager#6]
sorry i talked to a few mod makers now, and they all say the same thing if they disable your stuff all there mods work, so clearly the issue is your mod xD xD

**Comment by blaxxun-boop** [comment]
That's not how this works.

Yes, the stacktrace tells you that ItemManager triggers the issue. But it is not the underlying issue. That would be some Unity issue. ItemManager isn't a mod. It's a tool for mod authors. There are several hundreds of mods using ItemManager, including some of the biggest mods for Valheim. And you are the only one reporting this issue.

I specifically tested the functionality on a Windows and Linux environment again and cannot reproduce this issue.
Something is wrong with your Unity installation. Please refrain from spamming this repo.
